### ISSUE TITLE
Train and Test

### ISSUE THREAD

**Issue by krishkk** [qlik-oss/sse-r-plugin#10]
Hi 

I was trying to perform a simple linear/logistic regression analysis using this plug-in. 

I am stuck with an issue with having training set and testing set in the same code.
Could anyone help me here out. 

Thanks

**Comment by qlik-aoh** [comment]
Hi,

I apologize for the late response for this issue.

There is no built-in support in Qlik Sense for this so we believe this is best achieved in the SSE-plugin itself, but this is not an area we have much experience of.

On http://branch.qlik.com there are some projects dealing with machine learning on SSE/AAI which might be interesting for you to look at. For additional related questions I can recommend #sse on Qlik Branch on Slack, https://qlikbranch-slack-invite.herokuapp.com/ where you can hopefully get quicker assistance by other users.

Thanks
