### ISSUE TITLE
ServerSideExtension.dll is missing

### ISSUE THREAD

**Issue by stephanegrimaud** [qlik-oss/sse-r-plugin#16]
### Description

ServerSideExtension.dll is missing

### Steps to Reproduce

1. Launch the Build Project step in Visual Studio
2. Get the error message "...\csharp\ServerSideExtension\bin\Debug\ServerSideExtension.dll' is missing"

##### Expected behavior

Get the executables located in  csharp/SSEtoRserve/bin folder

##### Actual behavior

Error message = "...\csharp\ServerSideExtension\bin\Debug\ServerSideExtension.dll' is missing"

##### Operating system where the SSE plugin is deployed

Windows 7 Professionnel

##### Qlik Sense

Server

**Comment by qlik-aoh** [comment]
Hi,

Thank you for the feedback. It sounds like we are missing a dependency for the project structure, I will look into that.

Meanwhile, if you either build the entire solution or first manually build the project "ServerSideExtension", "ServerSideExtension.dll" will be created for you.

Regards,
Markus Helgesson

**Comment by stephanegrimaud** [comment]
When building the project "ServerSideExtension", I've got this error message : "Command "V:\Techno R\R_in_QC sse-r-plugin\sse-r-plugin-master\csharp\ServerSideExtension\generate_SSE_Stubs_from_proto.bat V:\Techno R\R_in_QC sse-r-plugin\sse-r-plugin-master\csharp\ServerSideExtension\" stopped with code 9009."

Please also notice that even after following the steps described in the Get Started document, the 2 files ServerSideExtension.cs and ServerSideExtensionGrpc.cs are still missing.

Sorry. I am not a VB expert so I am a bit lost...

Thanks for your help.

Stéphane

**Comment by qlik-aoh** [comment]
Sounds like there is a problem generating the gRPC and protobuf files. Please try according to the step-by-step comment by sam-sla @ https://github.com/qlik-oss/sse-r-plugin/issues/3 and let us know if there are any problems (in as much detail as possible).
