### ISSUE TITLE
Error in Qlik Sense

### ISSUE THREAD

**Issue by shamitshah** [qlik-oss/sse-r-plugin#20]
### Description

Getting an error in Qlik Sense

![image](https://user-images.githubusercontent.com/26819402/33236109-94052e98-d284-11e7-8642-7922c343fe94.png)

### Steps to Reproduce

1. Followed all the steps as per the instructions. All seems to be ok.
2. 
![image](https://user-images.githubusercontent.com/26819402/33236143-5f4379ca-d285-11e7-87d7-0a28800249e2.png)

3. 
![image](https://user-images.githubusercontent.com/26819402/33236132-1f38a2f6-d285-11e7-8250-c956c6259a9c.png)

4. Uploaded a similar Titanic .csv file in the Qlik Sense script
![image](https://user-images.githubusercontent.com/26819402/33236170-a8fef288-d285-11e7-91e5-ad8f8115573e.png)

##### Expected behavior

Expected that there would be no errors in Qlik Sense

##### Actual behavior

Error message

##### Operating system where the SSE plugin is deployed
```
[ ] Windows
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[ ] Server
```
### Versions

* sse-r-plugin:
* Qlik Sense:
* Operating system:
* [Other relevant versions]

**Comment by tobiaslindulf** [comment]
It looks like your Qlik Sense Desktop does not has a connection to the R plugin (SSEtoRserve).
How does your settings.ini file look like? This is where you setup the connection from Qlik to the SSE plugin.
When Sense Desktop starts, the following logline in SSEtoRserve should be printed: "2017-11-27 11:13:43.8748|INFO|SSEtoRserve.RServeEvaluator|GetCapabilities called, returned (Qlik SSEtoRserve plugin), version (v1.0.0)". 
If not, then the connection setup is not valid.

I do not think your changes in the app or the csv file are wrong, only the connection setup to the plugin.

**Comment by shamitshah** [comment]
It's working fine.

This is what I have in the settings file:

![image](https://user-images.githubusercontent.com/26819402/33266663-8320675e-d3b1-11e7-919e-e3e4728a00dd.png)

I had 3 pop up windows relating to:
1) Rserve.exe
2) Qlik Sense Desktop
3) sse-r-plugin

Thanks

**Comment by tobiaslindulf** [comment]
ok, so if I understand you correctly, the R expressions are working fine in analysis mode (from the sheet) but you see problems only from the Qlik Sense Load script (reload)?
What version of Qlik Sense are you running?

**Comment by shamitshah** [comment]
Thanks, it's all working fine now.

**Comment by ecornes** [comment]
How was this issue resolved?  I have the same problem.
