### ISSUE TITLE
SSE-r-plugin to running

### ISSUE THREAD

**Issue by miskinmaz** [qlik-oss/sse-r-plugin#27]
Hi All,

After building and rebuilding the solution from csharp folder, no executable found at folder csharp/SSEtoRserve/bin... Please help if i have missed any steps.

Regards
Miskin M

**Comment by tobiaslindulf** [comment]
Which version have you downloaded? This is the latest: https://github.com/qlik-oss/sse-r-plugin/releases/tag/v1.2.0 
What Visual Studio do you use?
What does the build output console say, any errors?
Have Visual Studio downloaded all the needed NuGet packages?

**Comment by miskinmaz** [comment]
Hi,

I was building the solution in debug mode and not in release mode....
Thanks for the help..

Regards
