### ISSUE TITLE
Unable to map user defined function with QLIK

### ISSUE THREAD

**Issue by DeepanshuChamoli** [qlik-oss/sse-r-plugin#28]
Unable to map the "FuncDefs.json" file with QLIK

I am using sse-r-plugin-1.2.0-qlik-oss file and we have "FuncDefs.json"  where we have created few more functions. I have installed the package jsonlite too. But still not getting the uses created function in Qlik

Steps to Reproduce

I am very new to R so do not know how to proceed the same.

##### Operating system where the SSE plugin is deployed
```
[ ] Windows



```
##### Qlik Sense
[ ] Server
```


* sse-r-plugin: sse-r-plugin-1.2.0-qlik-oss
* Qlik Sense: November 2107
* Operating system: Windows 2012 R2
* R version - R-3.4.3-win



<img width="594" alt="function error" src="https://user-images.githubusercontent.com/35762342/35324710-8bbbe7e2-0117-11e8-9f62-a6a4e829f96c.png">

**Comment by tobiaslindulf** [comment]
Hi,
You also need to enable/point to that FuncDefs.json file in the "SSEtoRserve.exe.config" file by setting the following line to the json file location, like below:
`<setting name="functionDefinitionsFile" serializeAs="String">`
`     <value>.\FuncDefs.json</value>  <!-- Set to i.e. .\FuncDefs.json to add your own defined SSE functions. The file contains the description of the functions. -->`

Then, after you have restarted SSEtoRserve.exe, the output in the cmd prompt should show the following:
![image](https://user-images.githubusercontent.com/12842866/35326044-c28df264-00f5-11e8-89e7-473f706f0246.png)

After this, you have to restart Qlik Sense, then the functions should be available in Sense.

**Comment by DeepanshuChamoli** [comment]
Thank you Sir.. it works for me know.

Thanks a lot for your response

Regards
Deepanshu
