### ISSUE TITLE
scripts with linebreak fail in ScriptEvaluate functions

### ISSUE THREAD

**Issue by ralfbecher** [qlik-oss/sse-r-plugin#32]
https://github.com/qlik-oss/sse-r-plugin/blob/d552689333c78d2d8d6419c4774c804c08201d49/csharp/SSEtoRserve/RServeEvaluator.cs#L381

Change to:
var rResult = await EvaluateScriptInRserve(inputDataFrame, reqHash, scriptHeader.Script.Replace("\r", " "), rserveConn);

**Comment by tobiaslindulf** [comment]
Fixed in release https://github.com/qlik-oss/sse-r-plugin/releases/tag/v1.2.1
