### ISSUE TITLE
Forecast isuue

### ISSUE THREAD

**Issue by miskinmaz** [qlik-oss/sse-r-plugin#33]
Hi,

forecast()$mean is returning value which is not correct and same for all predicted years. Whereas the same code in R result in another number. Please help.

Regards
Miskin

**Comment by tobiaslindulf** [comment]
Hi, can you please provide an example sense app (and data) together with a description of which object and expression that is not working as expected. Otherwise it is very hard to help you.
Thanks!

**Comment by miskinmaz** [comment]
Hi,

Since I missed to sort qvds, it was resulting into a wrong output. At the time of running code in R, my csv file was sorted.

Thanks
