### ISSUE TITLE
Qlik Sense does not see plugin

### ISSUE THREAD

**Issue by i1ya-p3d** [qlik-oss/sse-r-plugin#35]
### Description

I tried to use R in Qlik Sense, but for some reasons it doesn't work.
Tried different versions of R (including 3.4.4) and SSEtoRserve (1.0, 1.2, 1.2.1).
I use Windows 10 and Qlik Sense 2018 February Patch 1. 
Repairing Qlik Sense hasn't helped. Tried changing ports.

Settings.ini:
![default](https://user-images.githubusercontent.com/38507818/38952328-e4d83e42-4353-11e8-8a7e-f40c66b56582.png)

Rserve:
![default](https://user-images.githubusercontent.com/38507818/38953218-b5b7ec68-4356-11e8-8e90-ef8f53f92dc8.png)

SSEtoRserve:
![default](https://user-images.githubusercontent.com/38507818/38952362-0243dc20-4354-11e8-89c8-60d74aa2094e.png)

And Qlik Sensen recognizes any functions neither in script nor in interface.
![default](https://user-images.githubusercontent.com/38507818/38952461-7139b406-4354-11e8-8799-e649bc105fc9.png)
![default](https://user-images.githubusercontent.com/38507818/38952475-7c1f3512-4354-11e8-9434-23fe6693a959.png)

### Steps to Reproduce

Started Reserve
Started SSEToRserve
Open Qlik Sense Desktop
Opened Demo app

##### Operating system where the SSE plugin is deployed
```
Windows 10
```
##### Qlik Sense
```
[ ] Desktop
```
### Versions

* sse-r-plugin: 1.0,1.2,1.2.1
* Qlik Sense: Feb 2018 Patch 1

**Comment by tobiaslindulf** [comment]
The setup looks correct.
Have you tried restarting Qlik Sense?
The SSEtoRServe should get a printout when Qlik Sense is starting up.
Also, where is your settings.ini located? In which folder?

**Comment by davidfloriang** [comment]
I have the same issue.

The setup looks correct. **Answer:** YES
Have you tried restarting Qlik Sense? **Answer:** YES
The SSEtoRServe should get a printout when Qlik Sense is starting up. **Answer:** No. The SSEtoRServe doesn't print out
Also, where is your settings.ini located? In which folder? **Answer:** C:\Users\{MyUser}\Documents\Qlik\Sense

Best Regards.

### Environment

**Operating system where the SSE plugin is deployed**

`Windows 7`

**Qlik Sense**

`[X] Desktop`

### Versions

- sse-r-plugin: v1.2.1
- Qlik Sense: Apr 2018

**Comment by i1ya-p3d** [comment]
I figured it out. For some reason, Qlik Sense ignores Settings.ini in C:\Users\\{MyUser}\Documents\Qlik\Sense. Then I edited file in  C:\Users\\{MyUser} \AppData\Local\Programs\Qlik\Sense\Engine, and it does work fine.

**Comment by davidfloriang** [comment]
Yes Sr. 

Already it does work fine.

Thanks.

**Comment by tobiaslindulf** [comment]
Nice that you figured that out. Hope it goes well. Closing the issue now.
