### ISSUE TITLE
Installing Visual Studio 2015 is an Issue

### ISSUE THREAD

**Issue by zuruprem** [qlik-oss/sse-r-plugin#5]
### Description
Installing Visual Studio 2015 is an Issue

### Steps to Reproduce
1) I downloaded vs2015.com_enu file into my Qlik Sense Server from Microsoft to install Visual Studio.
2) I tried install VS 2015, Then I got following error
![image](https://user-images.githubusercontent.com/25402337/27991762-8bbefcb4-6489-11e7-8e54-0adc0bfbb5bd.png)
3) As suggested above I downloaded KB2919355 patch but when I tried to install that patch, I got a message that this patch is not applicable for your machine. I understand that this KB2919355 patch is only applicable for windows 8.1
4) I struck in installing VS 2015.
5) Can I complete the setup explained here by using VS 2017 community version?
 

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

##### Operating system where the SSE plugin is deployed
```
[ ] Windows
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[ ] Server
```
### Versions

* sse-r-plugin:
* Qlik Sense:
* Operating system:
* [Other relevant versions]

**Comment by kjartan-qlik** [comment]
Hi @zuruprem, yes Visual Studio Community 2017 should work as well.

**Comment by zuruprem** [comment]
:+1:  Thank You.
