### ISSUE TITLE
Analytic Connector Name in QMC

### ISSUE THREAD

**Issue by CheckmateQlik** [qlik-oss/sse-r-plugin#6]
### Description

From my limited knowledge of getting this working, it seems you must name the Analytic Connector in the QMC 'R'.  This should be added to the instructions.

### Steps to Reproduce

1. Follow the instructions
2. Realize it doesn't work until you name the Analytic Connector 'R'
3. Be happy you got it working, then mad that it wasn't in the instructions.

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

##### Operating system where the SSE plugin is deployed
```
[ ] Windows
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[ ] Server
```
### Versions

* sse-r-plugin:
* Qlik Sense:
* Operating system:
* [Other relevant versions]

**Comment by kjartan-qlik** [comment]
Hi @CheckmateQlik,

thank you for bringing this to our attention. In theory you can use any name you want, but for the name to match the one used in the example apps it needs to be `R`. I will add this information immediately.
