### ISSUE TITLE
 Capability parameter value not available

### ISSUE THREAD

**Issue by ravi22saini** [qlik-oss/sse-r-plugin#9]
Hi Everyone,

I am facing a issue while fetching capability first parameter value in 2nd measure call from qlik sense dektop (please note i am using execute function and creating my own capability).

For example::
I have created a capability of type aggregation with 3 param values. when we call this capability from 
a chart who is having two measure, then the call for first measure works fine but in case of second measure i was not able to find the first value of capability parameter.

My capability call looks like 
R.GetTotalCost(Region,Year,Country);

In case of first measure i will get all the values, but in case of second i am getting only year and country.

Please help me with this issue.

Thanks in advance.

**Comment by qlik-aoh** [comment]
Hi,

Is it possible for you to provide us with a small example qvf-file and SSE-plugin-code where the problem can be seen?

Thanks,
Markus

**Comment by ravi22saini** [comment]
Hi Markus 

Thanks for reverting.

I have attached the dummy qvf and made necessary changes to RServeEvaluator class (Just replace the original file with the one I attached).
Just to give you quick idea about the issue I have attached the screenshot.


![issue](https://user-images.githubusercontent.com/31721143/30341774-e2818e7c-9814-11e7-8c7f-538e6280e446.jpg)
[SseExample.zip](https://github.com/qlik-oss/sse-r-plugin/files/1296964/SseExample.zip)
[RServeEvaluator.zip](https://github.com/qlik-oss/sse-r-plugin/files/1296966/RServeEvaluator.zip)

**Comment by tobiaslindulf** [comment]
Thank you for the detailed example. I have been able to reproduce the problem now and we are investigating it.

**Comment by tobiaslindulf** [comment]
We have now discovered that this is a bug in Qlik Sense when calling Aggregation functions in SSE.
The bug is corrected and fixed in Qlik Sense but we still do not know in which release of Qlik Sense the bugfix will be available.
A workaround for you, relating to your test/dummy qvf and the expressions in the chart, would be to change "G.Test('IND',SR_Year)" to "Aggr(G.Test('IND',SR_Year), SR_Year)".

**Comment by ravi22saini** [comment]
Thanks @tobiaslindulf for your response, please let me know when the bug get fixed in future update of qlik sense

**Comment by tobiaslindulf** [comment]
The mentioned bug above is now fixed in Qlik Sense November 2017 release. Closing this issue now.

**Comment by ravi22saini** [comment]
Thank you @tobiaslindulf
